# -*- coding: utf-8 -*-
"""prophet_inputs_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFmLfP77jOiTuucFmDhsZ5rA52gLMp7f
"""

import re
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd


# ============================================================
# 1) EXACT product -> product_category mapping
# ============================================================
PRODUCT_TO_CATEGORY: Dict[str, str] = {
    # (Keep your full mapping here exactly as you have it)
    # ...
}


# ============================================================
# 2) TXT -> JSON parser
# ============================================================
DASH_LINE = re.compile(r"^-{10,}\s*$")
EQUAL_LINE = re.compile(r"^={10,}\s*$")
ITEM_LINE = re.compile(r"^\s*(\d+,\d{2})\s+(.+?)\s+(\d+,\d{2})\s*$")


def _clean_line(s: str) -> str:
    s = s.replace("€", "").replace("�", "")
    s = re.sub(r"\s{2,}", " ", s)
    return s.rstrip()


def _parse_invoices(raw_txt_path: str) -> List[dict]:
    raw_txt_path = str(raw_txt_path)
    with open(raw_txt_path, "r", encoding="latin-1") as f:
        content = f.read()

    raw_invoices = re.split(r"FACTURA(?: SIMPLIFICADA(?:\s+ABONO)?)?", content)

    invoices: List[dict] = []
    for block in raw_invoices[1:]:
        lines = [_clean_line(ln) for ln in block.splitlines()]
        invoice = {"items": []}

        m_num = re.search(r"N.? Op\.\:\s+([A-Z0-9\-]+)", block)
        if m_num:
            invoice["invoice_number"] = m_num.group(1).strip()

        m_related = re.search(r">>\s*Doc\. Relacionado:\s*(T-\d+)", block)
        if m_related:
            invoice["related_invoice"] = m_related.group(1)

        m_date = re.search(r"(\d{2}/\d{2}/\d{4})", block)
        if m_date:
            invoice["date"] = m_date.group(1)

        m_loc = re.search(r"N.? Op\.\:\s+[A-Z0-9\-]+\s+([A-Za-z0-9/]+)", block)
        if m_loc:
            invoice["location"] = m_loc.group(1).strip()

        for ln in lines:
            m_total = re.search(r"Total\s+\(Impuestos Incl\.\)\s+(-?\d+,\d{2})", ln)
            if m_total:
                invoice["grand_total"] = float(m_total.group(1).replace(",", "."))
                break

        for ln in lines:
            m_pay = re.search(r"\b(Tarjeta|Efectivo)\b\s+(\d+,\d{2})", ln)
            if m_pay:
                invoice["payment_method"] = m_pay.group(1)
                invoice["amount_paid"] = float(m_pay.group(2).replace(",", "."))
                break

        # Items section detection
        items_start: Optional[int] = None
        for i, ln in enumerate(lines):
            if ln.strip().startswith("Uds.") and "Producto" in ln and "Importe" in ln:
                items_start = i + 1
                if items_start < len(lines) and DASH_LINE.match(lines[items_start]):
                    items_start += 1
                break

        items_end: Optional[int] = None
        if items_start is not None:
            for j in range(items_start, len(lines)):
                if DASH_LINE.match(lines[j]):
                    items_end = j
                    break

        # Parse item lines
        if items_start is not None and items_end is not None:
            for ln in lines[items_start:items_end]:
                if not ln.strip() or DASH_LINE.match(ln) or EQUAL_LINE.match(ln):
                    continue

                m_item = ITEM_LINE.match(ln)
                if not m_item:
                    qty_m = re.search(r"^\s*(\d+,\d{2})", ln)
                    prices = re.findall(r"(\d+,\d{2})", ln)
                    if qty_m and prices:
                        qty_str = qty_m.group(1)
                        price_str = prices[-1]
                        qty = float(qty_str.replace(",", "."))
                        price = float(price_str.replace(",", "."))
                        qty_end = qty_m.end()
                        price_start = ln.rfind(price_str)
                        product = ln[qty_end:price_start].strip()
                        if product:
                            invoice["items"].append(
                                {"product": product, "quantity": qty, "price": price}
                            )
                    continue

                qty = float(m_item.group(1).replace(",", "."))
                product = m_item.group(2).strip()
                price = float(m_item.group(3).replace(",", "."))
                invoice["items"].append({"product": product, "quantity": qty, "price": price})

        invoices.append(invoice)

    return invoices


# ============================================================
# 3) JSON -> df_invoices (one row per item)
# ============================================================
def _invoices_json_to_df(records: List[dict]) -> pd.DataFrame:
    rows = []
    for inv in records:
        inv_number = inv.get("invoice_number")

        invoice_type = None
        if isinstance(inv_number, str):
            if inv_number.startswith("TD-"):
                invoice_type = "TD"
            elif inv_number.startswith("T-"):
                invoice_type = "T"
            elif inv_number.startswith("F-"):
                invoice_type = "F"

        base = {
            "invoice_number": inv_number,
            "invoice_type": invoice_type,
            "related_invoice": inv.get("related_invoice"),
            "date": inv.get("date"),
            "location": inv.get("location"),
            "grand_total": inv.get("grand_total"),
            "payment_method": inv.get("payment_method"),
            "amount_paid": inv.get("amount_paid"),
        }

        items = inv.get("items") or []
        if items:
            for item in items:
                row = base.copy()
                row.update(
                    {
                        "product": item.get("product"),
                        "quantity": item.get("quantity"),
                        "price": item.get("price"),
                    }
                )
                rows.append(row)
        else:
            row = base.copy()
            row.update({"product": None, "quantity": None, "price": None})
            rows.append(row)

    df = pd.DataFrame(rows)
    df["date"] = pd.to_datetime(df["date"], format="%d/%m/%Y", errors="coerce")
    return df


# ============================================================
# 4) MAIN PIPELINE FUNCTION (public)
# ============================================================
def build_prophet_prediction_inputs(
    raw_txt_path: str,
    avg_weather_xlsx_path: str,
    horizon_days: int = 14,
    invoices_lag_days: int = 14,
    visitantes_baseline: int = 1934,
    visitantes_low: int = 1419,
    visitantes_high: int = 2739,
    drop_weather_cols: Tuple[str, ...] = ("tmax", "tmin", "prec"),
    drop_calendar_cols: Tuple[str, ...] = ("day", "month"),
    verbose: bool = True,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    End-to-end pipeline:
    txt -> JSON -> df_invoices -> remove related+TD -> map categories
    -> daily summary (+ units) -> build future dates -> lag invoices
    -> join avg weather -> engineered features -> 3 visitantes scenarios

    Returns:
      (future_baseline_df, future_low_df, future_high_df)
    """
    raw_txt_path = str(raw_txt_path)
    avg_weather_xlsx_path = str(avg_weather_xlsx_path)

    if not Path(raw_txt_path).exists():
        raise FileNotFoundError(f"raw_txt_path not found: {raw_txt_path}")
    if not Path(avg_weather_xlsx_path).exists():
        raise FileNotFoundError(f"avg_weather_xlsx_path not found: {avg_weather_xlsx_path}")
    if horizon_days <= 0:
        raise ValueError("horizon_days must be > 0")
    if invoices_lag_days <= 0:
        raise ValueError("invoices_lag_days must be > 0")

    # A) Parse txt -> json -> df_invoices
    input_json = _parse_invoices(raw_txt_path)
    df_invoices = _invoices_json_to_df(input_json)

    if verbose:
        print(f"Extracted {len(input_json)} invoices")
        print(f"Invoice-item rows: {df_invoices.shape[0]}")

    # B) Remove related invoices + TD invoices
    related_invoices = (
        df_invoices["related_invoice"].dropna().astype(str).str.strip().unique().tolist()
    )

    df_invoices = df_invoices.loc[~df_invoices["invoice_number"].isin(related_invoices)].copy()
    df_invoices = df_invoices.loc[df_invoices["invoice_type"].astype(str).str.strip().ne("TD")].copy()

    # C) Map categories (exact mapping)
    df_invoices["product_category"] = df_invoices["product"].map(PRODUCT_TO_CATEGORY)

    # D) Daily summary: revenue + invoice count
    invoice_level = (
        df_invoices.groupby("invoice_number", as_index=False)
        .agg(date=("date", "first"), grand_total=("grand_total", "first"))
    )
    invoice_level["date"] = pd.to_datetime(invoice_level["date"], errors="coerce")
    invoice_level["date_day"] = invoice_level["date"].dt.normalize()

    daily_summary = (
        invoice_level.groupby("date_day", as_index=False)
        .agg(total_revenue=("grand_total", "sum"), count_invoices=("invoice_number", "nunique"))
        .sort_values("date_day")
    )

    # E) Units per category per day + join to daily_summary
    df_invoices["date_day"] = df_invoices["date"].dt.normalize()
    daily_units_pivot = (
        df_invoices.groupby(["date_day", "product_category"], as_index=False)["quantity"]
        .sum()
        .pivot(index="date_day", columns="product_category", values="quantity")
        .fillna(0)
    )
    daily_units_pivot.columns = [f"units_{c}" for c in daily_units_pivot.columns]

    daily_summary_enriched = (
        daily_summary.merge(daily_units_pivot.reset_index(), on="date_day", how="left")
        .sort_values("date_day")
    )
    unit_cols = [c for c in daily_summary_enriched.columns if c.startswith("units_")]
    daily_summary_enriched[unit_cols] = daily_summary_enriched[unit_cols].fillna(0)

    # F) Build base future frame (history + horizon)
    future_df = daily_summary_enriched.copy()
    future_df["date_day"] = pd.to_datetime(future_df["date_day"], errors="coerce")
    future_df = future_df.sort_values("date_day").set_index("date_day").asfreq("D")  # fixed daily frequency [web:10]
    future_df["day"] = future_df.index.day
    future_df["month"] = future_df.index.month
    future_df = future_df.reset_index()

    last_hist_date = future_df["date_day"].max()
    future_dates = pd.date_range(start=last_hist_date + pd.Timedelta(days=1), periods=horizon_days, freq="D")

    future_rows = pd.DataFrame({"date_day": future_dates})
    future_rows["day"] = future_rows["date_day"].dt.day
    future_rows["month"] = future_rows["date_day"].dt.month
    future_rows["count_invoices"] = np.nan
    future_rows["total_revenue"] = np.nan
    for c in unit_cols:
        future_rows[c] = np.nan

    future_df = pd.concat([future_df, future_rows], ignore_index=True)
    future_df = future_df.sort_values("date_day").set_index("date_day").asfreq("D")

    # G) Lag feature (uses shift(periods=...)) [web:4]
    lag_col = f"invoices_lag_{invoices_lag_days}"
    future_df[lag_col] = future_df["count_invoices"].shift(invoices_lag_days)

    future_df = future_df.reset_index().dropna(subset=[lag_col])

    max_hist_day = daily_summary_enriched["date_day"].max()
    future_df = future_df.loc[future_df["date_day"] > max_hist_day].copy()

    future_df = future_df.drop(columns=["count_invoices", "total_revenue"], errors="ignore")

    # H) Join average weather + engineered features
    avg_weather_df = pd.read_excel(avg_weather_xlsx_path)
    future_df = future_df.merge(avg_weather_df, on=["month", "day"], how="left")

    if "tmax" in future_df.columns and "tmin" in future_df.columns:
        future_df["temp_range"] = future_df["tmax"] - future_df["tmin"]
    if "prec" in future_df.columns:
        future_df["is_rain"] = (future_df["prec"] > 0).astype(int)
        future_df["is_heavy_rain"] = (future_df["prec"] >= 10).astype(int)
    if "tmed" in future_df.columns:
        future_df["is_hot"] = (future_df["tmed"] >= 30).astype(int)
        future_df["is_cold"] = (future_df["tmed"] <= 6).astype(int)

    future_df = future_df.rename(columns={"date_day": "ds"})

    # I) Three visitantes scenarios
    future_1_baseline_df = future_df.copy()
    future_2_low_df = future_df.copy()
    future_3_high_df = future_df.copy()

    future_1_baseline_df["visitantes_cxf"] = visitantes_baseline
    future_2_low_df["visitantes_cxf"] = visitantes_low
    future_3_high_df["visitantes_cxf"] = visitantes_high

    cols_to_drop = list(drop_calendar_cols) + list(drop_weather_cols)
    future_1_baseline_df = future_1_baseline_df.drop(columns=cols_to_drop, errors="ignore")
    future_2_low_df = future_2_low_df.drop(columns=cols_to_drop, errors="ignore")
    future_3_high_df = future_3_high_df.drop(columns=cols_to_drop, errors="ignore")

    extra_drop = [c for c in future_1_baseline_df.columns if c.startswith("units_")] + ["is_rain", "is_heavy_rain"]
    future_1_baseline_df = future_1_baseline_df.drop(columns=extra_drop, errors="ignore")
    future_2_low_df = future_2_low_df.drop(columns=extra_drop, errors="ignore")
    future_3_high_df = future_3_high_df.drop(columns=extra_drop, errors="ignore")

    final_cols = ["ds", "invoices_lag_14", "tmed", "temp_range", "is_hot", "is_cold", "visitantes_cxf"]
    future_1_baseline_df = future_1_baseline_df.reindex(columns=final_cols)
    future_2_low_df = future_2_low_df.reindex(columns=final_cols)
    future_3_high_df = future_3_high_df.reindex(columns=final_cols)

    return future_1_baseline_df, future_2_low_df, future_3_high_df
